blank_issues_enabled: false
contact_links:
  - name: "📊 Voir le tableau de bord du projet"
    url: "https://github.com/users/Louis-XII/projects/2"
    about: "Consultez l'avancement global d'AutomationPlus."
